enjoy-digital/litepcie

setup.py

This way not only travis config knows about the dependency and 'python setup.py test' can be used directly.

add pyyaml to setup.py

---

litepcie/software/kernel/main.c

cdev.h is required for cdev_init() and other calls; it was probably included through some other headers on older kernel versions, but at least on 5.4.0 it has to be added.

software: include cdev.h

---

litepcie/software/kernel/init.sh
litepcie/software/kernel/main.c

The main improvement is that class_create() / device_create() handle device node creation without manual mknod. Some smaller cleanups include the use of managed functions which do not require manual cleanup (pcim_enable_device() obsoletes pci_disable_msi and pci_disable_device,  devm_kzalloc() - free). Char devices are now created per device in probe() instead of bulk in init().

Improve kernel driver

---

litepcie/software/kernel/main.c

match definitions used in main.c to those present in config.h

software: fix definitions

---

litepcie/frontend/dma.py

splitted -> split, datas -> data, mB -> Mb, negociate -> negotiate

dma: fix mistypes in comments

---

litepcie/software/kernel/main.c

This is a follow-up to the discussion in https://github.com/enjoy-digital/litepcie/pull/26 - managed functions take care of the region release.

kernel: remove unnecessary call to pci_release_regions() on device remove

---

litepcie/frontend/axi.py
litepcie/frontend/dma.py
litepcie/gen.py

This PR adds an AXI4 slave bridge, modifies DMA cores to allow providing descriptors via streams (when `with_csr` is set to `false`) and replaces AXI-Lite slave bridge in `litepcie_gen` with AXI4 bridge.
This offers significantly better performance compared to AXI-Lite bridge - in the same test case (AXI CDMA reads and writes to host side buffers) I observed about 5MB/s for AXI-Lite and 1200MB/s for AXI4
This requires enjoy-digital/litex#734

Add AXI4 slave bridge

---

litepcie/software/kernel/config.h
litepcie/software/kernel/flags.h
litepcie/software/kernel/litepcie.h
litepcie/software/kernel/main.c

Linux kernel code strictly follows one code style:
https://www.kernel.org/doc/html/latest/process/coding-style.html
I believe it is therefore beneficial to have kernel-related code like this module formatted the same way so that people working on it can work in a setting they are used to.
Most fixes are about indentation and spacing and are done by [checkpatch](https://www.kernel.org/doc/html/latest/dev-tools/checkpatch.html) itself; one redundant dev_err() is removed because kzalloc reports errors itself; struct file_operations is set const.

software/kernel: fix source formatting

---

litepcie/software/kernel/main.c

pci_get_drvdata does not fail if probe() succeeded; remove() is not called if probe() failed
references:
https://elixir.bootlin.com/linux/latest/source/drivers/net/ethernet/intel/e1000/e1000_main.c#L1260
https://elixir.bootlin.com/linux/latest/source/drivers/video/fbdev/nvidia/nvidia.c#L1427
https://www.spinics.net/lists/netdev/msg504207.html

remove unneeded checks in litepcie_pci_remove

---

litepcie/software/kernel/Makefile
litepcie/software/kernel/liteuart.c
litepcie/software/kernel/main.c

Addressing https://github.com/enjoy-digital/litepcie/issues/35 - now one gets working /dev/ttyLXU0 if CSR_UART_XOVER_RXTX_ADDR was defined and when liteuart module is loaded.
liteuart from the mainline kernel temporarily added here with a few changes:
- few bugs were found in liteuart_probe() and liteuart_remove() - one by me, other ones by Johan Hovold - that's now under review in [LKML](https://marc.info/?l=linux-serial&r=1&b=202111&w=2)
- for me writes to OFF_EV_PENDING during read were causing missing symbols - comparing to litepcie_util uart_test() I removed it and now it works fine; not sure if that is really needed when the driver is used on a "real" SoC
- on a "real" SoC the driver gets a memory region resource and this way the base offset, but in this use case it just needs an …

register liteuart for crossover UART

---

litepcie/software/kernel/Makefile

This is convenient when working on litepcie, as the kernel build system doesn't (?) support automatic dependency tracking.

Make kernel object depend on relevant headers.

---

litepcie/software/user/liblitepcie/litepcie_dma.c
litepcie/software/user/liblitepcie/litepcie_flash.c
litepcie/software/user/liblitepcie/litepcie_helpers.c
litepcie/software/user/liblitepcie/litepcie_helpers.h

I first was using `libexplain`, which gives slightly nicer error messages, but that library doesn't seem packaged everywhere (i.e. not on Arch Linux here).

Check all ioctls.

---

litepcie/software/user/liblitepcie/litepcie_dma.c

I was testing a version of the driver where only `mmap` is supported, and noticed that `read`/`write` file operations, although unsupported, didn't properly fail.

Check return code of file operations.

---

litepcie/software/kernel/main.c
litepcie/software/user/Makefile
litepcie/software/user/helpers.c
litepcie/software/user/helpers.h
litepcie/software/user/liblitepcie/litepcie_dma.c
litepcie/software/user/litepcie_test.c
litepcie/software/user/litepcie_util.c

- dev_dbg -> dev_err for DMA overflows and underflows
- write all patterns before starting verifying them in dma_test
- zero read buffers in dma_test for better error detection
- minor edits

software fixes

---

litepcie/software/user/Makefile
litepcie/software/user/liblitepcie/liblitepcie.h

Use `-fPIC`, and add `extern C` to headers.

Improve liblitepcie reusability

---

litepcie/phy/s7pciephy.py

LitePCIeMSIMultiVector and its corresponding kernel module are designed for multiple MSI vectors. Add this configuration to help people choose the vector number they need.

add configurable MSI vector number

---

litepcie/phy/usppciephy.py
litepcie/phy/xilinx_usp_gen2_x4/pcie_usp_support.v
litepcie/phy/xilinx_usp_gen3_x16/pcie_usp_support.v
litepcie/phy/xilinx_usp_gen3_x4/pcie_usp_support.v
litepcie/phy/xilinx_usp_gen3_x8/pcie_usp_support.v
litepcie/phy/xilinx_usp_hbm_gen2_x4/pcie_usp_support.v
litepcie/phy/xilinx_usp_hbm_gen3_x4/pcie_usp_support.v

Note we also fix the cfg_negotiated_width and cfg_current_speed
signal with in the support wrapper since those have different
encoding than in the UltraScale blocks.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

phy: Add detailled status for UltraScale Plus PCIe PHY

---

contrib/pcie_ltssm_trace.py
litepcie/phy/common.py
litepcie/phy/s7pciephy.py
litepcie/phy/uspciephy.py
litepcie/phy/usppciephy.py

This records every state that the LTSSM state reported by the PHY
goes through and pushes it to a FIFO that's readable via the CSR
interface.
A small python script that reads and decodes that FIFO is also
included (through UARTBone/JTAGBone or such. _NOT_ the PCIe bridge !)
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

phy: Add optional LTSSMDebug module

---

litepcie/frontend/dma.py

The new mode allows synchronization of TX streams to RX streams upon a PPS event, or only PPS with TX and RX streams unsynchronized. This clarifies that in "PPS-only" mode, both TX and RX streams can be "flowgated" by the synchronizer module, but they may remain unsynced to each other.

Clarify comments about LitePCIeDMASynchronizer

---

litepcie/software/kernel/main.c

Since kernel 5.18 `pci_set_dma_mask` is more available and must be recplaced by `dma_set_mask`.

litepcie/software/kernel/main.c: fix build with kernel >= 5.18 (pci_set_dma_mask -> dma_set_mask)

---

litepcie/software/kernel/main.c

According to: https://www.kernel.org/doc/Documentation/DMA-API-HOWTO.txt
This should match the address width supported by the gateware.
In this case, PCIe only supports 32/64bit masks.

set `DMA_BIT_MASK` to `DMA_ADDR_WIDTH`

---

bench/kc705.py

This fixes the following error trying to build the kc705 bench kernel driver
```
johnsimons@johnsimons-ubuntu:~/git/litex/litepcie/bench/build/kc705/driver/kernel$ sudo ./init.sh 
[sudo] password for johnsimons: 
Module not compiled
In file included from ./include/linux/pci-dma-compat.h:8,
from ./include/linux/pci.h:2461,
from /home/johnsimons/git/litex/litepcie/bench/build/kc705/driver/kernel/main.c:27:
/home/johnsimons/git/litex/litepcie/bench/build/kc705/driver/kernel/main.c: In function ‘litepcie_pci_probe’:
/home/johnsimons/git/litex/litepcie/bench/build/kc705/driver/kernel/main.c:1045:43: error: ‘DMA_ADDR_WIDTH’ undeclared (first use in this function)
1045 |  ret = pci_set_dma_mask(dev, DMA_BIT_MASK(DMA_ADDR_WIDTH));
|                                           ^~~~~~~~~~~~~~ …
```

Added DMA_ADDR_WIDTH constant to kc705.py bench to fix kernel driver

---

litepcie/common.py
litepcie/core/endpoint.py
litepcie/tlp/common.py
litepcie/tlp/depacketizer.py
litepcie/tlp/packetizer.py

- Rework Packetizer/Depacketizer to be more modular (and allow individual selection of capabilities: Request, Completion, Configuration, PTM TLPs).
- Add Configuration TLP definitions/layouts.
- Add PTM TLP definitions/layouts.
- Implement Configuration support in Depacketizer (not required in Packetizer since returning Completion).
- Implement PTM support in Packetizer/Depacketizer.
For now, Configuration and PTM TLPs can now just be sent/received to/from  the User logic. Logic to handle this still has to be done and integrated.
> Note: As a bonus, making Packetizer/Depacketizer more modular allow some optimization on Ultrascale(+) were we can only select Completion or Request support (see  https://github.com/enjoy-digital/litepcie/commit/33c52fc2b339464bf89e6b7f5e7f9e6ccfc2e06b).

Add Configuration and PTM TLP support.

---

litepcie/software/kernel/main.c

Linux Kernel 6.5 has slightly different syntax related to creating a class, which I ifdef-ed so the the driver will compile against the latest kernels.

litepcie/software/kernel: updated main.c to support Linux kernel 6.5

---

litepcie/phy/usppciephy.py
litepcie/software/kernel/liteuart.c
litepcie/tlp/packetizer.py

This completes gen4 support on the gateware side.

phy/usppciephy: Use double wide axis for gen4

---

litepcie/gen.py
litepcie/phy/gw5apciephy.py

This PR aims at providing a basic PHY for Gowin Arora V FPGAs. This PHY is a wrapper around Gowin's IP generated with IP Core Generator GUI tool.
Current state is:
- MMAP: OK
- MSI: OK
- DMAs: WiP.
**Note:**: Archives of generated code are used for the X1 and X4 PHYs since it does not seems possible to dynamically produce them from the .ipc file.

phy/gw5apciephy.py: Added basic PHY for Gowin Arora V FPGAs

---

litepcie/software/kernel/liteuart.c

Starting with kernel 6.10.0, some changes in UART breaks driver (everything related to circ_buf was removed).
This PR adds fix for liteuart.c when build with new kernel.
Fix issue #141

software/kernel/liteuart.c: fixed build with kernel >= 6.10 (circ_buf removed) (issue #141)

---

litepcie/gen.py
litepcie/phy/lfcpnxpciephy.py

This PR aims at providing a basic PHY for Lattice Certus NX Pro FPGAs. This PHY is a wrapper around Lattice IP generated with IP Generator GUI tool.
Current state is:
-  MMAP: OK
-  MSI: WIP
-  DMAs: WiP.
- 1.1.0 version: upgrade to 2.3.1 is required
Note:: Archives of generated code is used  for lowlevel PHYs, build time is possible but needs to have previously downloaded IP Generator libraries.

phy/lfcpnxpciephy.py: Added basic PHY for Lattice Certus NX Pro FPGAs

---

litepcie/software/kernel/liteuart.c

With a continuous UART RX stream at high speed, timer callback took a too long time before finishing, or don't finish.
As the result some interrupts are blocked and the kernel hang with the need to force stop/start the computer.
This PR adds a workqueue to delegate RX FIFO read out of the timer callback.
To avoid to adds to long latency, this workqueue is only used after a 256 read sequence. This keep the default behavior in a normal uses.
Note to myself/TODO/FIXME: When the read is transfered to the workqueue, timer callback must avoid to call `mod_timer` and let the workqueue to do this task at the end of execution.

software/kernel/liteuart.c: added a workqueue to avoid blocking timer callback

---

README.md
litepcie/software/__init__.py
setup.py

`distutils` was removed in Python 3.12, causing litepcie to crash when trying to use it.

Remove usage of `distutils`
